### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by kcousot** [thunlp/OpenKE#104]
Mixed tabs and spaces in config/Config.py.
Untabify fixes the issue.

```
Traceback (most recent call last):
  File "example_train_transe.py", line 1, in <module>
    import config
  File "[...]/OpenKE/config/__init__.py", line 1, in <module>
    from .Config import Config
  File "[...]/OpenKE/config/Config.py", line 378
    test_r = np.array([r] * self.entTotal)
                                         ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by ShulinCao** [comment]
I have fixed the issue, thanks.
