### ISSUE TITLE
TransR AttributeError

### ISSUE THREAD

**Issue by kcousot** [thunlp/OpenKE#105]
Steps to Reproduce:
1. Copy `example_train_transe.py` to `example_train_transr.py`
2. Line 31, replace `models.TransE` by `models.TransR`.

```
Input Files Path : ./benchmarks/FB15K/
The toolkit is importing datasets.
The total of relations is 1345.
The total of entities is 14951.
The total of train triples is 483142.
The total of test triples is 59071.
The total of valid triples is 50000.
The total of test triples is 59071.
The total of valid triples is 50000.
Traceback (most recent call last):
  File "example_train_transr.py", line 31, in <module>
    con.set_model(models.TransR)
  File "[...]/OpenKE/config/Config.py", line 278, in set_model
    self.trainModel = self.model(config = self)
  File "[...]/OpenKE/models/Model.py", line 79, in __init__
    self.loss_def()
  File "[...]/OpenKE/models/TransR.py", line 47, in loss_def
    p_h = tf.reshape(self._transfer(pos_matrix, pos_h_e), [-1, config.rel_size])
  File "[...]/OpenKE/models/TransR.py", line 12, in _transfer
    return tf.batch_matmul(transfer_matrix, embeddings)
AttributeError: 'module' object has no attribute 'batch_matmul'
```

EDIT: could it be `tf.linalg.matmul` ?
https://www.tensorflow.org/api_docs/python/tf/linalg/matmul

**Comment by ShulinCao** [comment]
You can follow the steps in example/train_transr.py

**Comment by kcousot** [comment]
Oh boy... did I overlook the example directory ? Sorry for the inconvenience :-/
`example/train_transr.py` is running, thanks !
