### ISSUE TITLE
save_model failed, seemed to be Tensorflow version incompatibility? 

### ISSUE THREAD

**Issue by chenmosha** [thunlp/OpenKE#122]
Hi, I'm running the code here:  https://github.com/IBM/knowledge-enabled-textual-entailment/blob/master/kg-embeddings/run.py

which uses OpenKE,  code from master branch(git clone https://github.com/thunlp/OpenKE.git) , I'm using Python3.6(Anaconda3) and tf 1.4.0,  it shows the training has finished, but model saving has failed, the tracelog is as follows(the last 100 log lines):

863.2617454528809
9974
880.4120888710022
9975
883.9015874862671
9976
861.2490739822388
9977
855.5091338157654
9978
876.1705832481384
9979
843.062840461731
9980
844.4841361045837
9981
841.2082171440125
9982
891.6720337867737
9983
874.0380201339722
9984
877.5717487335205
9985
888.2820992469788
9986
852.8435292243958
9987
916.7220225334167
9988
867.9723272323608
9989
862.5464777946472
9990
845.4844813346863
9991
864.1797904968262
9992
907.849452495575
9993
920.2699346542358
9994
901.7849793434143
9995
875.8704609870911
9996
847.8520827293396
9997
876.0049986839294
9998
866.5371298789978
9999
902.0099873542786
Input Files Path : /home/user/experiments/NLI/knowledge-enabled-textual-entailment/kg-embeddings/../data/conceptnet/
The toolkit is importing datasets.
The total of relations is 38.
The total of entities is 1100497.
The total of train triples is 3017855.
**TypeError: expected bytes, PosixPath found**

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chenmosha.cms/software/anaconda3/envs/torch_kg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
SystemError: <built-in function TF_Run> returned a result with an error set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chenmosha.cms/software/anaconda3/envs/torch_kg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/chenmosha.cms/software/anaconda3/envs/torch_kg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/chenmosha.cms/software/anaconda3/envs/torch_kg/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: Unable to get element as bytes.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 174, in <module>
    run()
  File "run.py", line 170, in run
    config.run()
  File "/home/user/experiments/NLI/knowledge-enabled-textual-entailment/kg-embeddings/OpenKE/config/Config.py", line 329, in run
    self.save_tensorflow()
  File "/home/user/experiments/NLI/knowledge-enabled-textual-entailment/kg-embeddings/OpenKE/config/Config.py", line 208, in save_tensorflow
    self.saver.save(self.sess, self.exportName)
  File "/home/user/software/anaconda3/envs/torch_kg/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1573, in save
    {self.saver_def.filename_tensor_name: checkpoint_file})
  File "/home/user/software/anaconda3/envs/torch_kg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/user/software/anaconda3/envs/torch_kg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/user/software/anaconda3/envs/torch_kg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/user/software/anaconda3/envs/torch_kg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Unable to get element as bytes.

I guess it is due to Tensorflow incompatible issue?

**Comment by THUCSTHanxu13** [comment]
Because the path in the code is bytes not str. You can change the code in the run.py as follows,

    # Model parameters will be exported via torch.save() automatically.
    config.set_export_files(str(OUTPUT_PATH / "transh.pt"))
    # Model parameters will be exported to json files automatically.
    # (Might cause IOError if the file is too large)
    config.set_out_files(str(OUTPUT_PATH / "transh_embedding.vec.json"))
To test the results faster, you can change  "config.set_train_times(1)"
