### ISSUE TITLE
Tensorflow error when doing test the second time

### ISSUE THREAD

**Issue by SvetaZlobina** [thunlp/OpenKE#161]
Hello! Thank you for such an interesting framework. 
While trying to use it as a backend for a web-server in my student project, I need to do con.test() multiple times in the same process. And here is the problem: the first time it works great, but the second - I get an InvalidArgumentError from Tensorflow.

`Traceback (most recent call last):
  File "/Users/shine/FilesRoot/Diplom/OpenKE/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/Users/shine/FilesRoot/Diplom/OpenKE/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/Users/shine/FilesRoot/Diplom/OpenKE/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[40091] = 140496569662840 is not in [0, 40943)
	 [[{{node model/predict/embedding_lookup_4}}]]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/private/var/folders/k_/w8hdxvpn7f362xr3c8v82w200000gn/T/AppTranslocation/B88D11A3-37DF-413E-A956-47496CDE3CC2/d/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/private/var/folders/k_/w8hdxvpn7f362xr3c8v82w200000gn/T/AppTranslocation/B88D11A3-37DF-413E-A956-47496CDE3CC2/d/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/shine/FilesRoot/Diplom/OpenKE/examples/train_complex.py", line 38, in <module>
    print(con.test()[0])
  File "/Users/shine/FilesRoot/Diplom/OpenKE/config/Config.py", line 366, in test
    res = self.test_step(self.test_h, self.test_t, self.test_r)
  File "/Users/shine/FilesRoot/Diplom/OpenKE/config/Config.py", line 317, in test_step
    predict = self.sess.run(self.trainModel.predict, feed_dict)
  File "/Users/shine/FilesRoot/Diplom/OpenKE/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/Users/shine/FilesRoot/Diplom/OpenKE/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/shine/FilesRoot/Diplom/OpenKE/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/Users/shine/FilesRoot/Diplom/OpenKE/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[40091] = 140496569662840 is not in [0, 40943)
	 [[node model/predict/embedding_lookup_4 (defined at /Users/shine/FilesRoot/Diplom/OpenKE/models/ComplEx.py:54) ]]
Caused by op 'model/predict/embedding_lookup_4', defined at:
  File "/private/var/folders/k_/w8hdxvpn7f362xr3c8v82w200000gn/T/AppTranslocation/B88D11A3-37DF-413E-A956-47496CDE3CC2/d/PyCharm.app/Contents/helpers/pydev/pydevconsole.py", line 386, in <module>
    pydevconsole.start_client(host, port)
  File "/private/var/folders/k_/w8hdxvpn7f362xr3c8v82w200000gn/T/AppTranslocation/B88D11A3-37DF-413E-A956-47496CDE3CC2/d/PyCharm.app/Contents/helpers/pydev/pydevconsole.py", line 327, in start_client
    process_exec_queue(interpreter)
  File "/private/var/folders/k_/w8hdxvpn7f362xr3c8v82w200000gn/T/AppTranslocation/B88D11A3-37DF-413E-A956-47496CDE3CC2/d/PyCharm.app/Contents/helpers/pydev/pydevconsole.py", line 174, in process_exec_queue
    more = interpreter.add_exec(code_fragment)
  File "/private/var/folders/k_/w8hdxvpn7f362xr3c8v82w200000gn/T/AppTranslocation/B88D11A3-37DF-413E-A956-47496CDE3CC2/d/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_code_executor.py", line 106, in add_exec
    more = self.do_add_exec(code_fragment)
  File "/private/var/folders/k_/w8hdxvpn7f362xr3c8v82w200000gn/T/AppTranslocation/B88D11A3-37DF-413E-A956-47496CDE3CC2/d/PyCharm.app/Contents/helpers/pydev/pydevconsole.py", line 84, in do_add_exec
    command.run()
  File "/private/var/folders/k_/w8hdxvpn7f362xr3c8v82w200000gn/T/AppTranslocation/B88D11A3-37DF-413E-A956-47496CDE3CC2/d/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_console_types.py", line 35, in run
    self.more = self.interpreter.runsource(text, '<input>', symbol)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/code.py", line 74, in runsource
    self.runcode(code)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/private/var/folders/k_/w8hdxvpn7f362xr3c8v82w200000gn/T/AppTranslocation/B88D11A3-37DF-413E-A956-47496CDE3CC2/d/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/private/var/folders/k_/w8hdxvpn7f362xr3c8v82w200000gn/T/AppTranslocation/B88D11A3-37DF-413E-A956-47496CDE3CC2/d/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/shine/FilesRoot/Diplom/OpenKE/examples/train_complex.py", line 34, in <module>
    con.set_model(models.ComplEx)
  File "/Users/shine/FilesRoot/Diplom/OpenKE/config/Config.py", line 285, in set_model
    self.trainModel = self.model(config = self)
  File "/Users/shine/FilesRoot/Diplom/OpenKE/models/Model.py", line 82, in __init__
    self.predict_def()
  File "/Users/shine/FilesRoot/Diplom/OpenKE/models/ComplEx.py", line 54, in predict_def
    predict_t_e2 = tf.nn.embedding_lookup(self.ent2_embeddings, predict_t)
  File "/Users/shine/FilesRoot/Diplom/OpenKE/venv/lib/python3.7/site-packages/tensorflow/python/ops/embedding_ops.py", line 316, in embedding_lookup
    transform_fn=None)
  File "/Users/shine/FilesRoot/Diplom/OpenKE/venv/lib/python3.7/site-packages/tensorflow/python/ops/embedding_ops.py", line 133, in _embedding_lookup_and_transform
    result = _clip(array_ops.gather(params[0], ids, name=name),
  File "/Users/shine/FilesRoot/Diplom/OpenKE/venv/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/Users/shine/FilesRoot/Diplom/OpenKE/venv/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 3273, in gather
    return gen_array_ops.gather_v2(params, indices, axis, name=name)
  File "/Users/shine/FilesRoot/Diplom/OpenKE/venv/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3748, in gather_v2
    "GatherV2", params=params, indices=indices, axis=axis, name=name)
  File "/Users/shine/FilesRoot/Diplom/OpenKE/venv/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/Users/shine/FilesRoot/Diplom/OpenKE/venv/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/shine/FilesRoot/Diplom/OpenKE/venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/Users/shine/FilesRoot/Diplom/OpenKE/venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()
InvalidArgumentError (see above for traceback): indices[40091] = 140496569662840 is not in [0, 40943)
	 [[node model/predict/embedding_lookup_4 (defined at /Users/shine/FilesRoot/Diplom/OpenKE/models/ComplEx.py:54) ]]
`

Seems like there is some cache in Tensorflow memory after the first time. I tried `tf.restore_default_graph()` and  `con.sess.close()`, but it didn't solve the problem. Could you please give a hint, what to do?

**Comment by THUCSTHanxu13** [comment]
Before the second time to run con.test(). You can run con.initTest() first.

Such as 
...
con.initTest()
con.test()
...

**Comment by THUCSTHanxu13** [comment]
After finishing running the first time test(), the pointer of the dataset points to the last instance in the dataset. If you directly run the next time test(), this pointer will make the code crash. Hence, you can initialize the test settings again.

**Comment by THUCSTHanxu13** [comment]
This details can be founded from https://github.com/thunlp/OpenKE/blob/master/base/Test.h
