### ISSUE TITLE
GPU or CPU out of memory for big graph ?

### ISSUE THREAD

**Issue by walton-wang929** [thunlp/OpenKE#285]
Traceback (most recent call last):
  File "train_transe_360KG.py", line 49, in <module>
    trainer.run()
  File "/data2/x/graph/OpenKE/openke/config/Trainer.py", line 58, in run
    self.model.cuda()
  File "/data2/x/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 463, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/data2/x/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/data2/x/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/data2/x/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/data2/x/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 463, in <lambda>
    return self._apply(lambda t: t.cuda(device))

### **RuntimeError: CUDA out of memory. Tried to allocate 57.31 GiB (GPU 0; 31.75 GiB total capacity; 0 bytes already allocated; 15.38 GiB free; 0 bytes reserved in total by PyTorch)**

Datasize:
![image](https://user-images.githubusercontent.com/35922098/97771425-c4199080-1b77-11eb-81b1-4ec211ea446c.png)

![image](https://user-images.githubusercontent.com/35922098/97771517-86693780-1b78-11eb-9cdc-cde13e83619b.png)

### How to slove this problem?

**Comment by walton-wang929** [comment]
I saw the OpenKE ACL paper just now, see that GPU didn't make any improvements for KG task.
![image](https://user-images.githubusercontent.com/35922098/97772080-6f2d4880-1b7e-11eb-8adc-6a945c20d31d.png)

### I wonder threads number is a linear scale relation to speed ?  anyone try 16/32 threads?

**Comment by walton-wang929** [comment]
### switch to  CPU training, out of memory again, I have **256G** Mem in my sever.

The toolkit is importing datasets.
The total of relations is 1825826.
The total of entities is 76914149.
The total of train triples is 382606627.
Input Files Path : /data2/wangtao1/graph/360KG/

The total of test triples is 58387397.
The total of valid triples is 58387435.

Finish initializing...
  0%|                                                                                                                                                     | 0/1000 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "train_transe_360KG.py", line 49, in <module>
    trainer.run()
  File "/data2/x/graph/OpenKE/openke/config/Trainer.py", line 93, in run
    loss = self.train_one_step(data)
  File "/data2/x/graph/OpenKE/openke/config/Trainer.py", line 50, in train_one_step
    'mode': data['mode']
  File "/data2/x/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data2/x/graph/OpenKE/openke/module/strategy/NegativeSampling.py", line 24, in forward
    score = self.model(data)
  File "/data2/x/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data2/x/graph/OpenKE/openke/module/model/TransE.py", line 67, in forward
    h = self.ent_embeddings(batch_h)
  File "/data2/x/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data2/x/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 126, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/data2/x/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 1852, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)

### **RuntimeError: [enforce fail at CPUAllocator.cpp:65] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 79582172800 bytes. Error code 12 (Cannot allocate memory)**

### 79582172800 bytes =74 GB, but I have 256 Mem, why crash?

**Comment by mdabedr** [comment]
I am also having the same issue. I tried decreasing the batchsize but it fails to get to training so I am guessing the issue is not related to batch size.

**Comment by luzhongqiu** [comment]
some issues :(  I have tried set batch_size=1, but also OOM.

**Comment by ignaciot** [comment]
@walton-wang929 have you figured out how to solve this? I'm running into the same issue, still haven't found a configuration that works for a large graph.

**Comment by yhshu** [comment]
Is there any solution right now? thanks.

**Comment by ignaciot** [comment]
I just noticed this issue was closed as "completed", has a fix been pushed for it?
