### ISSUE TITLE
Running OpenKE on CPU

### ISSUE THREAD

**Issue by mscsedu** [thunlp/OpenKE#294]
I want to run OpenKE code on cpu and remove the .cuda() from where it was used. Now I am getting the following error:

Input Files Path : ./benchmarks/FB15K237/
The total of test triples is 20466.
The total of valid triples is 17535.
Finish initializing...
  0%|                                                                          | 0/1000 [00:00<?, ?it/s]70746
Traceback (most recent call last):
  File "train_transe_FB15K237.py", line 40, in <module>
    trainer.run()
  File "C:\Users\Dell\CIPL\OpenKE\openke\config\Trainer.py", line 93, in run
    loss = self.train_one_step(data)
  File "C:\Users\Dell\CIPL\OpenKE\openke\config\Trainer.py", line 50, in train_one_step
    'mode': data['mode']
  File "C:\Users\Dell\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Dell\CIPL\OpenKE\openke\module\strategy\NegativeSampling.py", line 24, in forward
    score = self.model(data)
  File "C:\Users\Dell\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Dell\CIPL\OpenKE\openke\module\model\TransE.py", line 70, in forward
    h = self.ent_embeddings(batch_h)
  File "C:\Users\Dell\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Dell\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\nn\modules\sparse.py", line 110, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "C:\Users\Dell\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\nn\functional.py", line 1110, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: index out of range at c:\programdata\miniconda3\conda-bld\pytorch_1533094653504\work\aten\src\th\generic/THTensorMath.cpp:352

Any Idea why I am getting this error?
I am using the default parameters and just trying to run the code as it is.

**Comment by LiuYuemei111** [comment]
Have you tried setting `use_gpu = False` in `Traner()` and `Tester()`  in train_transe_FB15K237.py?
`
trainer = Trainer(model = model, data_loader = train_dataloader, train_times = 1000, alpha = 1.0, use_gpu = False)
`
`
tester = Tester(model = transe, data_loader = test_dataloader, use_gpu = False)
`
