### ISSUE TITLE
I keep getting [WinError 193] %1 is not a valid Win32 application error and can't run the examples\train_transe_FB15K237.py

### ISSUE THREAD

**Issue by lthlong0310** [thunlp/OpenKE#302]
I keep getting this error.
Traceback (most recent call last):
  File "D:/LONG/LEARNING/SourceCode/OpenKE/train_transe_FB15K237.py", line 9, in <module>
    train_dataloader = TrainDataLoader(
  File "D:\LONG\LEARNING\SourceCode\OpenKE\openke\data\TrainDataLoader.py", line 42, in __init__
    self.lib = ctypes.cdll.LoadLibrary(base_file)
  File "C:\Users\Ly T-Long\anaconda3\envs\py38\lib\ctypes\__init__.py", line 459, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\Ly T-Long\anaconda3\envs\py38\lib\ctypes\__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

I don't know why it happen and how to fix it.
Thank you.

**Comment by LiuYuemei111** [comment]
Are you running on a window system? Some packages used in C++ do not support compilation on windows. You can use it on Linux system.
