### ISSUE TITLE
OSError: exception: access violation reading 0xFFFFFFFFFFFFFFE8

### ISSUE THREAD

**Issue by marja-w** [thunlp/OpenKE#304]
Hello,
I am trying to run examples\train_transe_FB15K237.py and I am getting the following error:

`C:\Users\Marja\anaconda3\envs\env_pytorch\python.exe C:/Users/Marja/PycharmProjects/OpenKE/train_transe_FB15K237.py
Traceback (most recent call last):
  File "C:/Users/Marja/PycharmProjects/OpenKE/train_transe_FB15K237.py", line 17, in <module>
    neg_rel = 0)
  File "C:\Users\Marja\PycharmProjects\OpenKE\openke\data\TrainDataLoader.py", line 75, in __init__
    self.read()
  File "C:\Users\Marja\PycharmProjects\OpenKE\openke\data\TrainDataLoader.py", line 79, in read
    self.lib.setInPath(ctypes.create_string_buffer(self.in_path.encode(), len(self.in_path) * 2))
OSError: exception: access violation reading 0xFFFFFFFFFFFFFFE8`

I already tried changing relative to absolute paths and the command "cp examples/train_transe_FB15K237.py ./".

**Comment by LiuYuemei111** [comment]
Are you running on a window system? Some packages used in C++ do not support compilation on windows. You can use it on Linux system.
