### ISSUE TITLE
 [Errno 2] No such file or directory: './checkpoint/transe.ckpt'

### ISSUE THREAD

**Issue by Just-For-Fun77** [thunlp/OpenKE#324]
Finish initializing...
Epoch 999 | loss: 2.381932: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [2:02:31<00:00,  7.35s/it]
Traceback (most recent call last):
  File "train_transe_FB15K237.py", line 41, in <module>
    transe.save_checkpoint('./checkpoint/transe.ckpt')
  File "/home/centos_study/OpenKE/openke/module/BaseModule.py", line 21, in save_checkpoint
    torch.save(self.state_dict(), path)
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 376, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './checkpoint/transe.ckpt'
这是什么问题，怎么解决？

**Comment by zjwu0522** [comment]
mkdir checkpoint

**Comment by Just-For-Fun77** [comment]
谢谢🙏

发自我的iPhone
