### ISSUE TITLE
RuntimeError: index out of range at c:\a\w\1\s\tmp_conda_3.6_062715\conda\conda-bld\pytorch-cpu_1550384979956\work\aten\src\th\generic/THTensorEvenMoreMath.cpp:191

### ISSUE THREAD

**Issue by feng-1985** [thunlp/OpenKE#327]
When running the example - python train_transe_FB15K237.py   
This error founded. I just set the cpu mode and didn't change anything else.

Traceback (most recent call last):
  File "train_transe_FB15K237.py", line 44, in <module>
    trainer.run()
  File "C:\Users\kiss\OpenKE\openke\config\Trainer.py", line 93, in run
    loss = self.train_one_step(data)
  File "C:\Users\kiss\OpenKE\openke\config\Trainer.py", line 50, in train_one_step
    'mode': data['mode']
  File "C:\software\Anacondas\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\kiss\OpenKE\openke\module\strategy\NegativeSampling.py", line 24, in forward
    score = self.model(data)
  File "C:\software\Anacondas\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\kiss\OpenKE\openke\module\model\TransE.py", line 67, in forward
    h = self.ent_embeddings(batch_h)
  File "C:\software\Anacondas\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\software\Anacondas\lib\site-packages\torch\nn\modules\sparse.py", line 118, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "C:\software\Anacondas\lib\site-packages\torch\nn\functional.py", line 1454, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: index out of range at c:\a\w\1\s\tmp_conda_3.6_062715\conda\conda-bld\pytorch-cpu_1550384979956\work\aten\src\th\generic/THTensorEvenMoreMath.cpp:191

**Comment by LiuYuemei111** [comment]
Are you running on a window system? Some packages used in C++ do not support compilation on windows. You can use it on Linux system.
