### ISSUE TITLE
报错：double free or corruption (!prev)

### ISSUE THREAD

**Issue by lpj0711** [thunlp/OpenKE#328]
0%|          | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/lpj/pwork/OpenKE-PyTorch/examples/train_transh_FB15K237.py", line 45, in <module>
    trainer.run()
  File "/home/lpj/pwork/OpenKE-PyTorch/openke/config/Trainer.py", line 94, in run
    loss = self.train_one_step(data)
  File "/home/lpj/pwork/OpenKE-PyTorch/openke/config/Trainer.py", line 53, in train_one_step
    loss.backward()
  File "/home/lpj/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/lpj/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: transform: failed to synchronize: cudaErrorAssert: device-side assert triggered
double free or corruption (!prev)

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by LiuYuemei111** [comment]
你是按照readme的步骤执行的么？ 请将train_transe_FB15K237.py文件复制到根目录下执行：
```bash
cp examples/train_transe_FB15K237.py ./
python train_transe_FB15K237.py
```
