### ISSUE TITLE
A question about running train_transr_FB15K237.py

### ISSUE THREAD

**Issue by FairyFali** [thunlp/OpenKE#367]
During running time, it appears an error, do you know how to solve it?
```
python train_transr_FB15K237.py
Input Files Path : ./benchmarks/FB15K237/
The toolkit is importing datasets.
The total of relations is 237.
The total of entities is 14541.
The total of train triples is 272115.
Input Files Path : ./benchmarks/FB15K237/
The total of test triples is 20466.
The total of valid triples is 17535.
Finish initializing...
Epoch 0 | loss: 211.796842: 100%|███████████████████████████████████████| 1/1 [00:01<00:00,  1.24s/it]
Finish initializing...
  0%|                                                                       | 0/20466 [00:00<?, ?it/s]
Epoch 19 | loss: 4.094270:   2%|▋                                 | 19/1000 [03:48<3:16:33, 12.02s/it]
Traceback (most recent call last):
  File "train_transr_FB15K237.py", line 61, in <module>
    trainer.run(test_dataloader)
  File "/home/gxb/workspace/OpenKE/openke/config/Trainer.py", line 104, in run
    mrr, mr, hit10, hit3, hit1 = student_tester.run_link_prediction(type_constrain=False)
  File "/home/gxb/workspace/OpenKE/openke/config/Tester.py", line 79, in run_link_prediction
    score = self.test_one_step(data_head)
  File "/home/gxb/workspace/OpenKE/openke/config/Tester.py", line 67, in test_one_step
    'mode': data['mode']
  File "/home/gxb/workspace/OpenKE/openke/module/model/TransR.py", line 98, in predict
    score = self.forward(data)
  File "/home/gxb/workspace/OpenKE/openke/module/model/TransR.py", line 75, in forward
    h = self._transfer(h, r_transfer)
  File "/home/gxb/workspace/OpenKE/openke/module/model/TransR.py", line 60, in _transfer
    e = torch.matmul(e, r_transfer).permute(1, 0, 2)
RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1579027003190/work/aten/src/THC/THCBlas.cu:368```

**Comment by helloxcq** [comment]
参考https://github.com/pytorch/pytorch/issues/17334 中，安装CUDA10及对应的PyTorch。

**Comment by FairyFali** [comment]
> 参考[pytorch/pytorch#17334](https://github.com/pytorch/pytorch/issues/17334) 中，安装CUDA10及对应的PyTorch。

I realized another reason. In the following lines of the model file `TransR.py`, they cannot deal with the size mismatch (I mean h.shape[0] != r_transfer.shape[0] or t.shape[0] != r_transfer.shape[0]) between h/t and t_transfer, so self._transfer will cause errors.
![image](https://user-images.githubusercontent.com/25873620/167569903-725e9e11-ad88-4787-a43c-eff07d09d3dc.png)

Therefore, I am trying to add some codes to make h, t, r, and r_transfer possess same shape[0].
