### ISSUE TITLE
IndexError: index out of range in self

### ISSUE THREAD

**Issue by Sure0520** [thunlp/OpenKE#370]
跑自己的数据集出现下面的错误
```
Input Files Path : ../benchmarks/grape/
The toolkit is importing datasets.
The total of relations is 11.
The total of entities is 6279.
The total of train triples is 7081.
Finish initializing...
  0%|                                                  | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/media/nwafu303/ssd/su/examples/train_transe_Grape.py", line 40, in <module>
    trainer.run()
  File "/media/nwafu303/ssd/su/openke/config/Trainer.py", line 93, in run
    loss = self.train_one_step(data)
  File "/media/nwafu303/ssd/su/openke/config/Trainer.py", line 50, in train_one_step
    'mode': data['mode']
  File "/home/nwafu303/anaconda3/envs/su/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/nwafu303/ssd/su/openke/module/strategy/NegativeSampling.py", line 24, in forward
    score = self.model(data)
  File "/home/nwafu303/anaconda3/envs/su/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/nwafu303/ssd/su/openke/module/model/TransE.py", line 69, in forward
    r = self.rel_embeddings(batch_r)
  File "/home/nwafu303/anaconda3/envs/su/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nwafu303/anaconda3/envs/su/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 160, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/nwafu303/anaconda3/envs/su/lib/python3.6/site-packages/torch/nn/functional.py", line 2044, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
free(): invalid size

Process finished with exit code 134
```

**Comment by Sure0520** [comment]
找到问题了，是数据集的问题，train2id中出现了relation2id没出现的id
