### ISSUE TITLE
RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 0] 

### ISSUE THREAD

**Issue by zhangxiaopingicon** [thunlp/OpenKE#371]
The problem is "RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous".
I used my  Chinese dataset in Ubuntu.

> Traceback (most recent call last):
  File "/home/tjdx/desktop/OpenKE-OpenKE-PyTorch-1/examples/test-TansD.py", line 41, in <module>
    trainer.run()
  File "/home/tjdx/desktop/OpenKE-OpenKE-PyTorch-1/openke/config/Trainer.py", line 93, in run
    loss = self.train_one_step(data)
  File "/home/tjdx/desktop/OpenKE-OpenKE-PyTorch-1/openke/config/Trainer.py", line 45, in train_one_step
    loss = self.model({
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tjdx/desktop/OpenKE-OpenKE-PyTorch-1/openke/module/strategy/NegativeSampling.py", line 25, in forward
    p_score = self._get_positive_score(score)
  File "/home/tjdx/desktop/OpenKE-OpenKE-PyTorch-1/openke/module/strategy/NegativeSampling.py", line 15, in _get_positive_score
    positive_score = positive_score.view(-1, self.batch_size).permute(1, 0)
RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous

Please help me.

**Comment by zhangxiaopingicon** [comment]
I know, when the data is less than 100  lines in  train2id.txt, the error is happend. so make sure tha data more rich
