### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by well-Wzg** [thunlp/OpenKE#389]
Traceback (most recent call last):
  File "train_transe_FB15K237.py", line 41, in <module>
    transe.save_checkpoint('./checkpoint/transe.ckpt')
  File "/root/ABC/openke/module/BaseModule.py", line 21, in save_checkpoint
    torch.save(self.state_dict(), path)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 369, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './checkpoint/transe.ckpt'

**Comment by Yvonne-sq** [comment]
I have encountered the same problem, have you solved it upstairs? How to solve it? thank you
