### ISSUE TITLE
Dimension mismatch error on increasing neg_rate

### ISSUE THREAD

**Issue by pushpankar** [thunlp/OpenKE#74]
```
Input Files Path : ./benchmarks/FB15K/
The toolkit is importing datasets.
The total of relations is 1345.
The total of entities is 14951.
The total of train triples is 483142.
Traceback (most recent call last):
  File "example_train_transe.py", line 27, in <module>
    con.run()
  File "/home/pushpankar/OpenKE/config/Config.py", line 272, in run
    loss = self.trainModel()
  File "/home/pushpankar/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pushpankar/OpenKE/models/TransE.py", line 45, in forward
    loss=self.loss_func(p_score, n_score)
  File "/home/pushpankar/OpenKE/models/TransE.py", line 29, in loss_func
    loss = criterion(p_score,n_score,y)
  File "/home/pushpankar/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pushpankar/miniconda3/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 754, in forward
    return F.margin_ranking_loss(input1, input2, target, self.margin, self.size_average)
  File "/home/pushpankar/miniconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1290, in margin_ranking_loss
    return _functions.loss.MarginRankingLoss.apply(input1, input2, target, margin, size_average)
  File "/home/pushpankar/miniconda3/lib/python3.6/site-packages/torch/nn/_functions/loss.py", line 160, in forward
    _output.add_(-1, input2)
RuntimeError: invalid argument 3: sizes do not match at /opt/conda/conda-bld/pytorch_1518244507981/work/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:271
```

**Comment by pushpankar** [comment]
On changing neg_rate from 1 to 10, input of max_margin_loss is:
p_score.shape
torch.Size([4831])

n_score.shape
torch.Size([48310])

**Comment by ShulinCao** [comment]
I have fixed this bug. Have a try!

**Comment by pushpankar** [comment]
It works now. Thanks.
