### ISSUE TITLE
Ambiguous dimension.

### ISSUE THREAD

**Issue by binjiaqm** [thunlp/OpenKE#8]
Try to run the example.py under python 3.5. I got the error:

Traceback (most recent call last):
  File "example.py", line 21, in <module>
    con.set_model(models.TransE)
  File "/home/deeplearning/OpenKE/config/Config.py", line 148, in set_model
    self.trainModel = self.model(config = self)
  File "/home/deeplearning/OpenKE/models/Model.py", line 63, in __init__
    self.input_def()
  File "/home/deeplearning/OpenKE/models/Model.py", line 42, in input_def
    self.batch_h = tf.placeholder(tf.int64, [config.batch_seq_size])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 1494, in placeholder
    shape = tensor_shape.as_shape(shape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_shape.py", line 800, in as_shape
    return TensorShape(shape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_shape.py", line 436, in __init__
    self._dims = [as_dimension(d) for d in dims_iter]
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_shape.py", line 436, in <listcomp>
    self._dims = [as_dimension(d) for d in dims_iter]
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_shape.py", line 378, in as_dimension
    return Dimension(value)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_shape.py", line 36, in __init__
    raise ValueError("Ambiguous dimension: %s" % value)
ValueError: Ambiguous dimension: 9662.84

Need to fix the it to force the number to be integer @ Config.py.

**Comment by DHready** [comment]
Have you solved the question? I have the question now.
